import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Providers from "@/components/providers";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { VideoProvider } from "@/lib/video/context";
import { GlobalTrailer } from "@/components/trailer/global-trailer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const logoFont = localFont({
  variable: "--font-logo",
  src: "../../public/fonts/Rationale-Regular.woff",
  display: "swap",
});

const popinsFont = localFont({
  variable: "--font-popins",
  src: "../../public/fonts/Poppins-Regular.woff2",
  display: "swap",
});

const tekturFont = localFont({
  variable: "--font-tektur",
  src: "../../public/fonts/Tektur-Regular.woff2",
  display: "swap",
});

const oswaldFont = localFont({
  variable: "--font-oswald",
  src: "../../public/fonts/Oswald-Regular.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        oswaldFont.variable,
        tekturFont.variable,
        popinsFont.variable,
        logoFont.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <NuqsAdapter>
              <Providers>
                <Header />
                <main>
                  <VideoProvider>
                    {children}
                    <GlobalTrailer />
                  </VideoProvider>
                </main>
                <Footer />
                <Toaster
                  position="bottom-right"
                  duration={5000}
                  richColors
                  closeButton
                />
              </Providers>
            </NuqsAdapter>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
